version: '3.5'

services:
    server:
        build: ./packages/cli
        environment:
            MONGO_HOST: mongo
            MONGO_PORT: 27017
            MONGO_USER: root
            MONGO_PASSWORD: secret
            WAIT_HOSTS: mongo:27017
        volumes:
            - ./:/app
        ports:
            - 3003:3003
        working_dir: '/app'
        command: yarn start
        links:
            - mongo
        depends_on:
            - mongo
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
            - ./data:/data/db
        ports:
            - 27017:27017
